using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace BambuFilamentImporter.Services;

public sealed record BugReportRequest(
    string Summary,
    string Steps,
    string Expected,
    string Actual,
    bool IncludeLogs,
    string ApplicationContext);

public sealed record BugReportResult(
    string ZipPath,
    string IssueUrl,
    string IssueBody);

public sealed class DiagnosticReportService
{
    public const string NewIssueUrl = "https://github.com/Zataralee/Bambu-Filament-Importer/issues/new";
    private const int MaxLogCharacters = 1_000_000;
    private readonly BambuPaths _paths;
    private readonly string _logDirectory;

    public DiagnosticReportService(BambuPaths paths, string? logDirectory = null)
    {
        _paths = paths;
        _logDirectory = logDirectory ?? AppLog.LogDirectory;
    }

    public BugReportResult Create(
        BugReportRequest request,
        PrinterDiscoveryResult discovery,
        string? outputDirectory = null)
    {
        if (string.IsNullOrWhiteSpace(request.Summary))
        {
            throw new InvalidOperationException("Enter a short bug summary before creating the report.");
        }

        var redactor = new DiagnosticRedactor(_paths);
        var timestamp = DateTime.Now;
        var reportDirectory = outputDirectory ?? AppLog.ReportDirectory;
        Directory.CreateDirectory(reportDirectory);
        var fileStem = $"BFI-Bug-Report-{timestamp:yyyyMMdd-HHmmss}-{SafeFilePart(request.Summary)}";
        var zipPath = UniquePath(Path.Combine(reportDirectory, fileStem + ".zip"));
        var stagingDirectory = Path.Combine(Path.GetTempPath(), "BFI-Report-" + Guid.NewGuid().ToString("N"));

        try
        {
            Directory.CreateDirectory(stagingDirectory);
            var diagnostics = BuildDiagnostics(discovery, request.ApplicationContext);
            File.WriteAllText(
                Path.Combine(stagingDirectory, "diagnostics.txt"),
                redactor.Redact(diagnostics) + Environment.NewLine);

            var issueBody = BuildIssueBody(request, discovery, Path.GetFileName(zipPath));
            File.WriteAllText(
                Path.Combine(stagingDirectory, "report.md"),
                redactor.Redact(issueBody) + Environment.NewLine);

            if (request.IncludeLogs)
            {
                CopySanitizedLogs(stagingDirectory, redactor);
            }

            File.WriteAllText(
                Path.Combine(stagingDirectory, "README.txt"),
                "This package was generated by Bambu Filament Importer. It contains a diagnostic summary, the report text, and optional sanitized BFI logs. It does not contain Bambu Studio configuration files, printer serial numbers, access codes, or account credentials." + Environment.NewLine);
            ZipFile.CreateFromDirectory(stagingDirectory, zipPath, CompressionLevel.Optimal, includeBaseDirectory: false);

            var title = Uri.EscapeDataString("[Bug]: " + request.Summary.Trim());
            var issueUrl = $"{NewIssueUrl}?template=bfi-diagnostic-report.md&title={title}";
            return new BugReportResult(zipPath, issueUrl, redactor.Redact(issueBody));
        }
        finally
        {
            try
            {
                if (Directory.Exists(stagingDirectory))
                {
                    Directory.Delete(stagingDirectory, recursive: true);
                }
            }
            catch
            {
                // Windows will eventually clean the temporary staging folder.
            }
        }
    }

    private string BuildDiagnostics(PrinterDiscoveryResult discovery, string applicationContext)
    {
        var version = Assembly.GetEntryAssembly()?.GetName().Version?.ToString(3) ?? "unknown";
        var builder = new StringBuilder()
            .AppendLine("Bambu Filament Importer diagnostics")
            .AppendLine($"Generated: {DateTimeOffset.Now:O}")
            .AppendLine($"BFI version: {version}")
            .AppendLine($"Windows: {RuntimeInformation.OSDescription}")
            .AppendLine($"Runtime: {RuntimeInformation.FrameworkDescription}")
            .AppendLine($"Architecture: {RuntimeInformation.ProcessArchitecture}")
            .AppendLine($"Bambu Studio version: {GetBambuStudioVersion()}")
            .AppendLine($"Bambu Studio running: {BambuProcess.IsStudioRunning()}")
            .AppendLine($"Bambu configuration found: {File.Exists(_paths.ConfigPath)}")
            .AppendLine($"Roaming system catalog found: {Directory.Exists(_paths.RoamingProfileRoot)}")
            .AppendLine($"Program system catalog found: {Directory.Exists(_paths.ProgramProfileRoot)}")
            .AppendLine($"Registered local device count: {discovery.RegisteredDeviceCount}")
            .AppendLine($"Unrecognized local device count: {discovery.UnrecognizedDeviceCount}")
            .AppendLine($"Printer discovery: {discovery.Status}")
            .AppendLine("Detected target models:");

        foreach (var printer in discovery.Printers)
        {
            builder.AppendLine($"- {printer.DisplayName}");
        }

        if (!string.IsNullOrWhiteSpace(applicationContext))
        {
            builder.AppendLine().AppendLine("BFI state:").AppendLine(applicationContext.Trim());
        }

        return builder.ToString();
    }

    private string GetBambuStudioVersion()
    {
        try
        {
            var profileDirectory = new DirectoryInfo(_paths.ProgramProfileRoot);
            var installDirectory = profileDirectory.Parent?.Parent;
            var executablePath = installDirectory is null ? null : Path.Combine(installDirectory.FullName, "bambu-studio.exe");
            if (executablePath is not null && File.Exists(executablePath))
            {
                return FileVersionInfo.GetVersionInfo(executablePath).ProductVersion ?? "unknown";
            }

            foreach (var manifestPath in new[]
            {
                Path.Combine(_paths.RoamingProfileRoot, "BBL.json"),
                Path.Combine(_paths.ProgramProfileRoot, "BBL.json")
            })
            {
                if (!File.Exists(manifestPath))
                {
                    continue;
                }

                var manifest = JsonNode.Parse(File.ReadAllText(manifestPath))?.AsObject();
                var catalogVersion = manifest?["version"]?.GetValue<string>();
                if (!string.IsNullOrWhiteSpace(catalogVersion))
                {
                    return "catalog " + catalogVersion;
                }
            }
        }
        catch
        {
            // Version data is useful but not required to create a report.
        }

        return "unknown";
    }

    private void CopySanitizedLogs(string stagingDirectory, DiagnosticRedactor redactor)
    {
        var sourcePaths = new List<string>();
        if (Directory.Exists(_logDirectory))
        {
            sourcePaths.AddRange(Directory.EnumerateFiles(_logDirectory, "*.log")
                .OrderByDescending(File.GetLastWriteTimeUtc)
                .Take(3));
        }

        var legacyErrorLog = Path.Combine(AppLog.DataDirectory, "error.log");
        if (_logDirectory.Equals(AppLog.LogDirectory, StringComparison.OrdinalIgnoreCase)
            && File.Exists(legacyErrorLog))
        {
            sourcePaths.Add(legacyErrorLog);
        }

        if (sourcePaths.Count == 0)
        {
            return;
        }

        var targetDirectory = Path.Combine(stagingDirectory, "logs");
        Directory.CreateDirectory(targetDirectory);
        foreach (var sourcePath in sourcePaths.Distinct(StringComparer.OrdinalIgnoreCase))
        {
            try
            {
                var contents = File.ReadAllText(sourcePath);
                if (contents.Length > MaxLogCharacters)
                {
                    contents = "[Earlier log content omitted]" + Environment.NewLine + contents[^MaxLogCharacters..];
                }

                File.WriteAllText(
                    Path.Combine(targetDirectory, Path.GetFileName(sourcePath)),
                    redactor.Redact(contents));
            }
            catch
            {
                // A locked log should not prevent the rest of the report from being created.
            }
        }
    }

    private static string BuildIssueBody(
        BugReportRequest request,
        PrinterDiscoveryResult discovery,
        string reportFileName)
    {
        var version = Assembly.GetEntryAssembly()?.GetName().Version?.ToString(3) ?? "unknown";
        var printerModels = discovery.Printers.Count == 0
            ? "None detected"
            : string.Join(", ", discovery.Printers.Select(printer => printer.DisplayName));
        return $"""
            ## Summary
            {request.Summary.Trim()}

            ## Steps to reproduce
            {Fallback(request.Steps)}

            ## Expected behavior
            {Fallback(request.Expected)}

            ## Actual behavior / error
            {Fallback(request.Actual)}

            ## Environment
            - BFI: {version}
            - Windows: {RuntimeInformation.OSDescription}
            - Detected printers: {printerModels}
            - Registered devices: {discovery.RegisteredDeviceCount}
            - Unrecognized devices: {discovery.UnrecognizedDeviceCount}

            ## Diagnostic package
            Attach `{reportFileName}` to this issue.
            """;
    }

    private static string Fallback(string value) =>
        string.IsNullOrWhiteSpace(value) ? "Not provided" : value.Trim();

    private static string SafeFilePart(string value)
    {
        var cleaned = Regex.Replace(value.Trim(), "[^A-Za-z0-9]+", "-").Trim('-');
        return string.IsNullOrWhiteSpace(cleaned) ? "Report" : cleaned[..Math.Min(cleaned.Length, 40)];
    }

    private static string UniquePath(string requestedPath)
    {
        if (!File.Exists(requestedPath))
        {
            return requestedPath;
        }

        var directory = Path.GetDirectoryName(requestedPath)!;
        var stem = Path.GetFileNameWithoutExtension(requestedPath);
        var extension = Path.GetExtension(requestedPath);
        for (var suffix = 2; ; suffix++)
        {
            var candidate = Path.Combine(directory, $"{stem}-{suffix}{extension}");
            if (!File.Exists(candidate))
            {
                return candidate;
            }
        }
    }

    private sealed class DiagnosticRedactor
    {
        private static readonly Regex UserPathPattern = new(
            @"(?i)\b[A-Z]:\\Users\\[^\\\s]+",
            RegexOptions.Compiled);
        private static readonly Regex IpAddressPattern = new(
            @"(?<![\d.])(?:25[0-5]|2[0-4]\d|1?\d?\d)(?:\.(?:25[0-5]|2[0-4]\d|1?\d?\d)){3}(?![\d.])",
            RegexOptions.Compiled);
        private static readonly Regex SecretPattern = new(
            @"(?i)\b(access[_ -]?code|token|password|secret)\s*[:=]\s*[^\s,;]+",
            RegexOptions.Compiled);
        private readonly IReadOnlyList<string> _sensitiveValues;

        public DiagnosticRedactor(BambuPaths paths)
        {
            _sensitiveValues = ReadSensitiveValues(paths)
                .Where(value => !string.IsNullOrWhiteSpace(value) && value.Length >= 3)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderByDescending(value => value.Length)
                .ToList();
        }

        public string Redact(string text)
        {
            var redacted = text;
            foreach (var sensitiveValue in _sensitiveValues)
            {
                redacted = redacted.Replace(sensitiveValue, "[redacted]", StringComparison.OrdinalIgnoreCase);
            }

            redacted = UserPathPattern.Replace(redacted, @"C:\Users\[redacted]");
            redacted = IpAddressPattern.Replace(redacted, "[redacted-ip]");
            return SecretPattern.Replace(redacted, "$1=[redacted]");
        }

        private static IEnumerable<string> ReadSensitiveValues(BambuPaths paths)
        {
            yield return Environment.UserName;
            yield return Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
            yield return Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            yield return Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);

            if (!File.Exists(paths.ConfigPath))
            {
                yield break;
            }

            JsonObject? config;
            try
            {
                var text = File.ReadAllText(paths.ConfigPath);
                var jsonText = text.Split("\n# MD5 checksum ", StringSplitOptions.None)[0].TrimEnd();
                config = JsonNode.Parse(jsonText)?.AsObject();
            }
            catch
            {
                yield break;
            }

            foreach (var sectionName in new[] { "access_code", "user_access_code" })
            {
                if (config?[sectionName] is not JsonObject section)
                {
                    continue;
                }

                foreach (var item in section)
                {
                    yield return item.Key;
                    if (item.Value is JsonValue value && value.TryGetValue<string>(out var secret))
                    {
                        yield return secret;
                    }
                }
            }

            var presetFolder = config?["app"]?["preset_folder"]?.GetValue<string>();
            if (!string.IsNullOrWhiteSpace(presetFolder))
            {
                yield return presetFolder;
            }
        }
    }
}
